version: 2.1
orbs:
  heroku: circleci/heroku@2.0.0
jobs:
  build:
    docker:
      - image: cimg/php:8.2.5
    steps:
      - checkout
      # Install Node.js and npm with elevated privileges
      - run:
          name: Install Node.js
          command: |
            sudo apt-get update
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
      # Download and cache PHP dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
      - run:
          name: Install PHP Dependencies
          command: composer install -n --prefer-dist
      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      # Install JavaScript dependencies and build Vite assets
      - run:
          name: Install JS Dependencies
          command: npm install
      - run:
          name: Build Vite
          command: npm run build

  deploy_app:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          name: Install Node.js
          command: |
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Install JS Dependencies
          command: npm install
      - run:
          name: Build Vite
          command: npm run build
      - heroku/deploy-via-git:
          force: true
      - run:
          name: Run Database Migrations
          command: heroku run --app=${HEROKU_APP_NAME} php artisan migrate

workflows:
  deploy:
    jobs:
      - build
      - deploy_app
